<a href="https://colab.research.google.com/github/JesusjrGalvez/Tutorial_numpy/blob/main/1_Create_an_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import numpy as np

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [55]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [56]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [57]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Create an array with specified data type

In [58]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)
print('Data Type: ' + str(arr.dtype))
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
Data Type: int16
int16


In [59]:
print(arr.dtype)

int16


### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [60]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
arr = np.arange(-10, 10+1, 5)
print(arr)

[-10  -5   0   5  10]


### Create an array of evenly spaced numbers within specified range
```np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)``` has 5 parameters:
- ```start```: start number (inclusive)
- ```stop```: end number (inclusive unless ```endpoint``` set to ```False```)
- ```num_of_elements```: number of elements contained in the array
- ```endpoint```: boolean value representing whether the ```stop``` number is inclusive or not
- ```retstep```: boolean value representing whether to return the step size

In [61]:
arr = np.linspace(2, 3, num=5)
print(arr)

[2.   2.25 2.5  2.75 3.  ]


In [62]:
arr, step_size = np.linspace(0, 5, 8, endpoint=False, retstep=True)
print(arr)
print('The step size is ' + str(step_size))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
The step size is 0.625


### Create an array of random values of given shape
```np.random.rand()``` method returns values in the range [0,1)

In [63]:
arr = np.random.rand(1, 10)
print(arr)

[[0.1157552  0.42667931 0.58408708 0.83216801 0.79182427 0.18651578
  0.98261948 0.24029637 0.15030248 0.27722194]]


In [64]:
arr = np.random.rand(3, 3)
print(arr)


[[0.56805767 0.31382589 0.4138018 ]
 [0.04785056 0.02782902 0.86233306]
 [0.28136123 0.9409143  0.91404467]]


### Create an array of zeros of given shape 
- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [65]:
zeros = np.zeros((2,3))
print(zeros)
arr = np.random.rand(1, 10)
print(arr)
print(np.zeros_like(arr))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0.4376865  0.41178427 0.86953542 0.09552746 0.98369306 0.46907286
  0.57293829 0.29658403 0.83258066 0.05258692]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [66]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Data Type: complex64


### Create an array of ones of given shape 
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [67]:
ones = np.ones((3,2))
arr = np.random.rand(1,10)
print(arr)
print(np.ones_like(arr))
print(ones)

[[0.09454934 0.83918601 0.59331233 0.0172862  0.23285764 0.68353776
  0.55337694 0.72704137 0.14881607 0.81719116]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [68]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int64


### Create an empty array of given shape 
- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [69]:
empty = np.empty((5,5))
# OJO LOS VALORES INICIALES NO SON CERO.

print(empty)

arr

[[4.9e-324 0.0e+000 0.0e+000 0.0e+000 0.0e+000]
 [0.0e+000 9.9e-324 0.0e+000 0.0e+000 0.0e+000]
 [0.0e+000 0.0e+000 1.5e-323 0.0e+000 0.0e+000]
 [0.0e+000 0.0e+000 0.0e+000 2.0e-323 0.0e+000]
 [0.0e+000 0.0e+000 0.0e+000 0.0e+000 2.5e-323]]


[[1, 2, 3], [4, 5, 6]]

In [70]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
empty = np.empty_like(arr)
print(empty)
print('Data Type: ' + str(empty.dtype))

[[1 2 3]
 [4 5 6]]
Data Type: int64


### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [71]:
full = np.full((4,4), 5)
print(full)

false = np.full((2, 4), False)
print(false)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[False False False False]
 [False False False False]]


In [86]:
arr = np.array([[1,2, 4, 5], [3,4, 5, 6]], dtype=np.float64)
print(arr)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[1. 2. 4. 5.]
 [3. 4. 5. 6.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]]
Data Type: float64


In [89]:
# THIS GIVES OFF AN ERROR. 
arr = np.array([1, 2], [1, 2, 3, 4])

TypeError: ignored

In [90]:
# BUT THIS IS OK
arr = [[1, 2], [1, 2, 3, 4]]
print(arr)

[[1, 2], [1, 2, 3, 4]]


### Create an array in a repetitive manner
- ```np.repeat(iterable, reps, axis=None)```: repeat each **element** by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions
    - ```axis```: which axis to repeat along, default is ```None``` which will flatten the input array and then repeat
- ```np.tile()```: repeat **the whole array** by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [122]:
# No axis specified, then flatten the input array first and repeat
arr = [[0, 1, 2], [3, 4, 5]]
print(arr)

# OJO para obtener el shape de un array no es array.shape() ni array.shape SINO np.shape(arr)
print(np.shape(arr))

print("-----")
arr1 = np.repeat(arr, 3, axis=0) # axis=0 repeats the columns. 
print(arr1)
print(np.shape(arr1))

# Notice that it repeated the columns by three

print("-----")
arr2 = np.repeat(arr, 3, axis=1) # axis=1 repeats the rows. 
print(arr2)
print(np.shape(arr2))

[[0, 1, 2], [3, 4, 5]]
(2, 3)
-----
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]
(6, 3)
-----
[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]
(2, 9)


In [117]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.shape(arr))
print(arr)
arr1 = np.repeat(arr, 3, axis=0) 
print(np.shape(arr1))
print(arr1)



(2, 3)
[[0, 1, 2], [3, 4, 5]]
(6, 3)
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [120]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.shape(arr))
print(arr)
arr1 = np.repeat(arr, 3, axis=1)
print(np.shape(arr1))
print(arr1)


(2, 3)
[[0, 1, 2], [3, 4, 5]]
(2, 9)
[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [121]:
# Repeat the whole array by a specified number of times
arr = [[0, 1, 2], [3, 4, 5]]
print(np.tile(arr, 3))

[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]


In [123]:
# Repeat along specified axes
# ESTO NO LO ENTIENDO
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


### Create an identity matrix of given size
- ```np.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [133]:
identity_matrix = np.eye(5)
print(identity_matrix)

print(np.fliplr(identity_matrix))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [79]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [80]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Create an array with given values on the diagonal

In [81]:
arr = np.random.rand(5,5)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.61823894 0.54481642 0.62082379 0.34074991 0.27019352]
 [0.63970167 0.25670709 0.55102103 0.76141891 0.35315383]
 [0.93126758 0.32351419 0.78469947 0.44002793 0.06169435]
 [0.69640097 0.44743113 0.88386489 0.06783044 0.53047787]
 [0.10520407 0.82502078 0.82830377 0.07871238 0.21709124]]
Values on the diagonal: [0.61823894 0.25670709 0.78469947 0.06783044 0.21709124]


In [82]:
# Not necessarily to be a square matrix
arr = np.random.rand(10,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.50864376 0.32798154 0.69221798]
 [0.02957214 0.48825743 0.78240888]
 [0.93522149 0.77683268 0.99694146]
 [0.41868536 0.14408345 0.26416024]
 [0.27728212 0.4824592  0.23909172]
 [0.69498039 0.55626721 0.55433522]
 [0.71096665 0.34004434 0.09536026]
 [0.91924067 0.63068432 0.26325023]
 [0.10455848 0.93519311 0.39725147]
 [0.58810482 0.71517032 0.20898966]]
Values on the diagonal: [0.50864376 0.48825743 0.99694146]


In [83]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Sorting

In [127]:
arr = np.array([[4, 6, 8], [1, 9, 2]])
print(arr)
print(np.shape(arr))

# Sorting by columns
arr1 = np.sort(arr, axis=0)
print(arr1)

#Sorting by rows
arr2 = np.sort(arr, axis=1)
print(arr2)

[[4 6 8]
 [1 9 2]]
(2, 3)
[[1 6 2]
 [4 9 8]]
[[4 6 8]
 [1 2 9]]
