<a href="https://colab.research.google.com/github/JesusjrGalvez/Tutorial_numpy/blob/main/4_Math_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import numpy as np
import math

In [67]:
arr = np.random.rand(5,5)
print(arr)

[[0.14372429 0.34026706 0.90604067 0.76294747 0.96510935]
 [0.55243393 0.79953229 0.00105921 0.975264   0.36150542]
 [0.46468092 0.55839128 0.73983578 0.19564373 0.1349729 ]
 [0.05674927 0.06719407 0.04496458 0.53826035 0.12873908]
 [0.78920057 0.05752513 0.71053274 0.30515986 0.2095316 ]]


### element-wise addition, subtraction, multiplication and division

In [68]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.14372429 10.34026706 10.90604067 10.76294747 10.96510935]
 [10.55243393 10.79953229 10.00105921 10.975264   10.36150542]
 [10.46468092 10.55839128 10.73983578 10.19564373 10.1349729 ]
 [10.05674927 10.06719407 10.04496458 10.53826035 10.12873908]
 [10.78920057 10.05752513 10.71053274 10.30515986 10.2095316 ]]
[[-9.85627571 -9.65973294 -9.09395933 -9.23705253 -9.03489065]
 [-9.44756607 -9.20046771 -9.99894079 -9.024736   -9.63849458]
 [-9.53531908 -9.44160872 -9.26016422 -9.80435627 -9.8650271 ]
 [-9.94325073 -9.93280593 -9.95503542 -9.46173965 -9.87126092]
 [-9.21079943 -9.94247487 -9.28946726 -9.69484014 -9.7904684 ]]
[[1.43724288 3.40267059 9.06040673 7.62947472 9.65109346]
 [5.5243393  7.99532293 0.01059207 9.75264004 3.61505419]
 [4.6468092  5.58391279 7.39835779 1.95643733 1.34972896]
 [0.56749272 0.67194074 0.44964584 5.38260353 1.28739076]
 [7.89200572 0.5752513  7.10532742 3.05159858 2.09531604]]
[[0.01437243 0.03402671 0.09060407 0.07629475 0.09651093]
 [0.05524339 0.0799

In [69]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


In [70]:
arr1 = np.array([[1, 2, 3], [10, 20, 30]])
print(arr1)
print(np.shape(arr1))
arr2 = np.transpose(arr1)
print(arr2)
print(np.shape(arr2))
print("\n")
arr = np.matmul(arr1, arr2)
print(arr)

# This however does not work
#print(np.multiply(arr1, arr2))

[[ 1  2  3]
 [10 20 30]]
(2, 3)
[[ 1 10]
 [ 2 20]
 [ 3 30]]
(3, 2)


[[  14  140]
 [ 140 1400]]


### element-wise exponentiation

The exponential function is e^x where e is a mathematical constant called Euler's number, approximately 2.718281

In [71]:
print(arr)
print(np.exp(arr))

[[  14  140]
 [ 140 1400]]
[[1.20260428e+06 6.32743171e+60]
 [6.32743171e+60            inf]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [72]:
print(math.pow(2.718281, 14))
print(math.pow(2.718281, 140))

1202599.1528756742
6.3271617325812746e+60


### element-wise logorithm

In [73]:
# natural log
print(arr)
print(np.log(arr))
print(np.log(np.e*np.e))
print(math.pow(np.e, 5))
print(np.e * np.e * np.e * np.e *np.e)
print(np.log(math.pow(np.e, 5))) 

[[  14  140]
 [ 140 1400]]
[[2.63905733 4.94164242]
 [4.94164242 7.24422752]]
2.0
148.41315910257657
148.41315910257657
5.0


In [74]:
# base 2
print(np.log2(arr))    
print(np.log2(16)) # 2ˆ4 = 16

[[ 3.80735492  7.12928302]
 [ 7.12928302 10.45121111]]
4.0


In [75]:
# base 10
print(np.log10(arr))    
print(np.log10(1000)) # 10 ^3 = 1000

[[1.14612804 2.14612804]
 [2.14612804 3.14612804]]
3.0


### element-wise square root

In [76]:
print(np.sqrt(arr))
arr5 = np.array([[4, 8, 16], [100, 10, 25]])
print(arr5)
print(np.sqrt(arr5))

[[ 3.74165739 11.83215957]
 [11.83215957 37.41657387]]
[[  4   8  16]
 [100  10  25]]
[[ 2.          2.82842712  4.        ]
 [10.          3.16227766  5.        ]]


### element-wise sine and cosine

In [77]:
print(np.sin(arr))
print(np.sin(60))
print(np.sin(np.pi/2))

[[ 0.99060736  0.98023966]
 [ 0.98023966 -0.91289604]]
-0.3048106211022167
1.0


In [78]:
print(np.cos(arr))
print(np.cos(np.pi))

[[ 0.13673722 -0.19781357]
 [-0.19781357  0.40819214]]
-1.0


### sum along a specified axis

In [79]:
# sum along the row
print(arr5)
print(np.sum(arr5, axis=0))    

[[  4   8  16]
 [100  10  25]]
[104  18  41]


In [80]:
# sum along the column
print(arr5)
print(np.sum(arr5, axis=1))    

[[  4   8  16]
 [100  10  25]]
[ 28 135]


### compute the min and max along a specified axis
Returns the minimum element across every row and column 😀

In [81]:
# calculate min along the column
print(arr5)
print(np.min(arr5, axis=0))

[[  4   8  16]
 [100  10  25]]
[ 4  8 16]


In [82]:
arr6 = np.array([[1, 2, 3.3 , 0.4, 5, 6], [10, 20, 30, 40, 50, 60], [100, 0.2, 7, 0.4, 0.5,7]])
print(arr6)
print("\n")
print(np.min(arr6, axis=0)) # axis=0 means operations done column wise
print("\n")
print(np.min(arr6, axis=1)) # axis=1 means operations done row wise

[[  1.    2.    3.3   0.4   5.    6. ]
 [ 10.   20.   30.   40.   50.   60. ]
 [100.    0.2   7.    0.4   0.5   7. ]]


[1.  0.2 3.3 0.4 0.5 6. ]


[ 0.4 10.   0.2]


Returns the minimum element across every row and column

In [83]:
# calculate max along the row
print(np.max(arr, axis=1))    
print(np.max(arr6, axis=1))

[ 140 1400]
[  6.  60. 100.]


In [84]:
# if axis not specified, calculate the max/min value of all elements
print(arr6)
print(np.max(arr6))
print(np.min(arr6))

[[  1.    2.    3.3   0.4   5.    6. ]
 [ 10.   20.   30.   40.   50.   60. ]
 [100.    0.2   7.    0.4   0.5   7. ]]
100.0
0.2


In [85]:
np.full((3, 6), np.max(arr6)) # calculates the max of arr6 across all elements and then a full matrix with that element.


array([[100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100.]])

### compute the indices of the min and max along a specified axis

In [86]:
# along the row
print(np.argmin(arr6, axis=0))
print(np.argmax(arr6, axis=0))

[0 2 0 0 2 0]
[2 1 1 1 1 1]


In [87]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[0 0]
[1 1]


In [88]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr6))
print(np.argmax(arr6))

13
12


### compute element-wise min and max of two arrays

In [89]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 7, 3, 8, 7])
print(arr1)
print(arr2)
a = sum(arr1)
b = sum(arr2)
print(a)
print(b)
print("-----")
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 3 5 7 9]
[0 7 3 8 7]
25
25
-----
[1 7 5 8 9]
[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [90]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print(arr1)
print('fractional: ', re)
print('integral: ', intg)

[9.67834966 5.21177703 9.29442831 6.10072665 2.25433326 2.02103562
 5.54589513 5.16370088 9.858161   2.74932294]
fractional:  [0.67834966 0.21177703 0.29442831 0.10072665 0.25433326 0.02103562
 0.54589513 0.16370088 0.858161   0.74932294]
integral:  [9. 5. 9. 6. 2. 2. 5. 5. 9. 2.]


### compute the mean

In [91]:
# compute the overall mean
print(arr)
print(np.mean(arr))

[[  14  140]
 [ 140 1400]]
423.5


In [92]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[ 77. 770.]


In [93]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[ 77. 770.]


### compute the median

In [94]:
# compute the overall median
print(np.median(arr))

140.0


In [95]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[ 77. 770.]


In [96]:
# compute the median along the column
print(np.median(arr, axis=1))

[ 77. 770.]


### compute the percentile

In [97]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.03205989 0.63041507 0.96844927]


### compute the standard deviation & variance

In [98]:
# compute the overall standard deviation
print(np.std(arr))

566.1243238017599


In [99]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[ 63. 630.]


In [100]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[ 63. 630.]


In [101]:
# compute the overall variance
print(np.var(arr))

320496.75


In [102]:
# compute the variance along the row
print(np.var(arr, axis=0))

[  3969. 396900.]


In [103]:
# compute the variance along the column
print(np.var(arr, axis=1))

[  3969. 396900.]


### compute the covariance & correlation

In [104]:
arr = np.random.rand(5,8)

In [105]:
print(np.cov(arr))

[[ 0.08970824 -0.04529594  0.00667622 -0.03101472  0.0002189 ]
 [-0.04529594  0.10383253  0.00643204 -0.03462986 -0.00737568]
 [ 0.00667622  0.00643204  0.14922326 -0.00143516  0.05276725]
 [-0.03101472 -0.03462986 -0.00143516  0.08231721  0.01799716]
 [ 0.0002189  -0.00737568  0.05276725  0.01799716  0.0882886 ]]


In [106]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[1.         0.37761044]
 [0.37761044 1.        ]]


### compute cumulative sum & product

In [107]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[0.91167244 0.73374518 0.10499104 0.86913819 0.86290781 0.32562759
  0.37994586 0.54318573]
 [1.38408296 1.05228898 1.04077862 1.09021966 1.25043241 0.41813989
  1.2897641  0.71284424]
 [1.89884805 2.03529876 1.16960328 1.69654242 1.34875457 1.1084022
  2.26599499 0.72535772]
 [2.0190483  2.26455403 1.68507146 2.55546104 1.67387801 2.0454888
  2.68690231 1.27025381]
 [2.73056333 2.48698557 1.78984799 3.11584518 1.69324115 2.67599257
  3.50896705 1.8206241 ]]


In [108]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[0.91167244 1.64541762 1.75040865 2.61954684 3.48245465 3.80808224
  4.1880281  4.73121383]
 [0.47241052 0.79095432 1.7267419  1.94782337 2.33534797 2.42786027
  3.3376785  3.50733702]
 [0.51476509 1.49777488 1.62659953 2.2329223  2.33124447 3.02150678
  3.99773767 4.01025115]
 [0.12020025 0.34945552 0.8649237  1.72384233 2.04896576 2.98605236
  3.40695968 3.95185577]
 [0.71151503 0.93394657 1.0387231  1.59910723 1.61847037 2.24897414
  3.07103889 3.62140918]]


In [109]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[9.11672438e-01 7.33745178e-01 1.04991038e-01 8.69138185e-01
  8.62907813e-01 3.25627589e-01 3.79945861e-01 5.43185726e-01]
 [4.30683653e-01 2.33729975e-01 9.82493097e-02 1.92150350e-01
  3.34397999e-01 3.01245577e-02 3.45681673e-01 9.21560813e-02]
 [2.21700909e-01 2.29758853e-01 1.26569337e-02 1.16505131e-01
  3.28787362e-02 2.07938468e-02 3.37465128e-01 1.15319335e-03]
 [2.66485056e-02 5.26734263e-02 6.52424666e-03 1.00068427e-01
  1.06896476e-02 1.94856352e-02 1.42041543e-01 6.28370545e-04]
 [1.89608123e-02 1.17162313e-02 6.83587901e-04 5.60767588e-02
  2.06985165e-04 1.22857664e-02 1.16767345e-01 3.45836482e-04]]


In [110]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[9.11672438e-01 6.68935256e-01 7.02322070e-02 6.10414929e-02
  5.26731812e-02 1.71518410e-02 6.51677099e-03 3.53981698e-03]
 [4.72410523e-01 1.50483442e-01 1.40820536e-01 3.11328114e-02
  1.20647301e-02 1.11613595e-03 1.01548084e-03 1.72284967e-04]
 [5.14765089e-01 5.06019121e-01 6.51877402e-02 3.95248108e-02
  3.88616508e-03 2.68247329e-03 2.61871329e-03 3.27692183e-05]
 [1.20200254e-01 2.75565409e-02 1.42045201e-02 1.22005269e-02
  3.96667719e-03 3.71712003e-03 1.56456304e-03 8.52524281e-04]
 [7.11515030e-01 1.58263384e-01 1.65822876e-02 9.29245089e-03
  1.79931047e-04 1.13447203e-04 9.32609458e-05 5.13280542e-05]]


### element-wise comparison

In [111]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [112]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]
