<a href="https://colab.research.google.com/github/JesusjrGalvez/Tutorial_numpy/blob/main/5_Slicing_%26_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [69]:
arr = np.arange(1, 21) # don't confuse range(10) with np.arange(10)
arr = np.array(np.arange(1, 101)).reshape((10,10))
print(arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [73]:
print(arr)
print(arr[8:]) # Slice two last rows of an array
print(arr[5: 7]) # Slice rows 5 to 7 (not including 7)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


### Select a row or column

In [74]:
print(arr[2]) # Select a row
print(arr[:, 0]) # Select a column. OJO indexes begin at ZERO
print(arr[4, 4]) # Selects an element. 

[21 22 23 24 25 26 27 28 29 30]
[ 1 11 21 31 41 51 61 71 81 91]
45


### select an element by row and column indices

In [75]:
print(arr[3][3]) # REMEMBER INDEXES START AT ZERO
# or more concisely
print(arr[3, 3])

34
34


### indexing with slicing

In [76]:
# slicing one dimension array
# https://youtu.be/PbKOrSottRQ?t=393
arr_1d = np.arange(1, 11)
print(arr_1d)
print(arr_1d[2:4])
print(arr_1d[6:]) # slice to the end of the array
print(arr_1d[:4]) # slice from the beginning of the array

[ 1  2  3  4  5  6  7  8  9 10]
[3 4]
[ 7  8  9 10]
[1 2 3 4]


In [48]:
print(arr)
print(arr[0:1, 4:6]) # From row 0 to 1 (not including 1) to column 4 to 6 (but not including 6)
#print(arr[(0, 1), (4,4)]) #

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[5 6]]


In [50]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
print(arr)
# equivalent to arr[0,:,:,:]
print(arr[0, ...])    

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### assign a scalar to a slice by broadcasting

In [ ]:
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print(arr)

[[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


### boolean indexing

In [53]:
arr1 = np.arange(25).reshape((5,5))
print(arr1)
bools = np.array([True, True, False, True, False])
print(bools)
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ True  True False  True False]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [54]:
# negate the condition
print(arr1[~bools])    

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [55]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])    

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [57]:
arr = np.random.rand(10,10)
print(arr)

[[0.22334476 0.08106413 0.4764313  0.43190244 0.17826398 0.56808525
  0.03389536 0.72433118 0.8552426  0.43139783]
 [0.60188921 0.1818351  0.55626192 0.11107943 0.69174665 0.69520121
  0.99378262 0.07101134 0.25047677 0.31582924]
 [0.50703774 0.21759091 0.01718883 0.23735894 0.1860161  0.70058645
  0.91070921 0.92397311 0.72578385 0.84756932]
 [0.7514296  0.3968802  0.6014458  0.04594561 0.32885656 0.33345684
  0.75421807 0.25027265 0.76771537 0.35579616]
 [0.97391768 0.33551967 0.67393235 0.85590843 0.84661185 0.88038212
  0.50091355 0.73510263 0.7817651  0.50498096]
 [0.39449349 0.50479773 0.82146414 0.77014202 0.67911143 0.54208374
  0.17599085 0.34555502 0.37585072 0.87486571]
 [0.41427555 0.02355276 0.73809957 0.1214986  0.86876323 0.18791134
  0.97971902 0.59883777 0.77634958 0.59377513]
 [0.88792598 0.57737104 0.68174277 0.763271   0.63993981 0.73097212
  0.62017718 0.02071701 0.81834994 0.12546246]
 [0.16258452 0.45967945 0.08491813 0.24949263 0.26847062 0.69101787
  0.86104852

In [ ]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])       

[0.29404208 0.06137223 0.59811053]


In [ ]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])    

[[0.09566854 0.2190723  0.6754328 ]
 [0.28997889 0.13675444 0.07718654]
 [0.15862308 0.45510309 0.94789792]]


### dimension inference

In [59]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr)
print(arr.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)


### find elements/indices by conditions

In [ ]:
arr = np.arange(16).reshape(4,4)

In [ ]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [ ]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [ ]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
